---
# deploy zabbix agent using ansible playbook
- name: Deploy zabbix 6.0 agent
  hosts: allovercloud
  become: true
  tasks:
    - name: install zabbix key
      rpm_key:
        key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
        state: present
    - name: Add Zabbix Repo repositories
      yum:
        name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
        state: present
    - name: install zabbix agent2
      yum:
        name: zabbix-agent2
        state: present
    - name: Update Server zabbix_agent2.conf
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp:  'Server=127.0.0.1'
        replace: 'Server='
    - name: Update ServerActive on zabbix_agent2.conf
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp:  'ServerActive=127.0.0.1'
        replace: 'ServerActive='
    - name: Update hostname on zabbix_agent2.conf
      replace:
        path: /etc/zabbix/zabbix_agent2.conf
        regexp:  'Hostname=Zabbix server'
        replace: 'Hostname={{ ansible_hostname }}'
    - name: Allow new incoming SYN packets on TCP port 10050.
      iptables:
        chain: INPUT
        protocol: tcp
        destination_port: 10050
        ctstate: ESTABLISHED,RELATED,NEW
        jump: ACCEPT
        comment: Accept zabbix connections.
    - name: enable and start zabbix_agent2 service
      systemd:
        name: zabbix-agent2
        state: started
        enabled: yes
