---
# deploy zabbix agent using ansible playbook
- name: Deploy zabbix 6.0 agent 
  hosts: 
  vars:
    repos:
   tasks:
     - name: Add Zabbix Repo repositories 
       yum:
         name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
         state: present
    - name: install zabbix agent2 
       yum:
         name: zabbix-agent2
         state: present
    - name: Register system
      redhat_subscription:
        activationkey: rhel7-kvm-guest.key
        org_id: gcloud
        force_register: yes
    - name: Disable all repos
      rhsm_repository:
        name: "*"
        state: disabled 
    - name: Enable repos
      rhsm_repository:
        name: "{{ repos }}"
        state: enabled     
    - name: Install katello-agent with yum
      yum:
        name: katello-agent
        state: latest
    - name: Maske sure goferd serviec is running
      systemd:
        name: goferd
        state: restarted
        enabled: yes

