---
# deploy zabbix agent using ansible playbook
- name: Deploy zabbix 6.0 agent 
  hosts: 
   tasks:
     - name: Add Zabbix Repo repositories 
       yum:
         name: https://repo.zabbix.com/zabbix/6.0/rhel/8/x86_64/zabbix-release-6.0-1.el8.noarch.rpm
         state: present
     - name: install zabbix agent2 
       yum:
         name: zabbix-agent2
         state: present
     - name: Update Server zabbix_agent2.conf
       replace:
         path: /etc/zabbix/zabbix_agent2.conf
         regexp:  'Server='
         replace: 'Server=10.30.11.151'
     - name: Update ServerActive on zabbix_agent2.conf
       replace:
         path: /etc/zabbix/zabbix_agent2.conf
         regexp:  'ServerActive='
         replace: 'ServerActive=10.30.11.151'
     - name: Update ServerActive on zabbix_agent2.conf
       replace:
         path: /etc/zabbix/zabbix_agent2.conf
         regexp:  'Hostname='
         replace: 'ansible_hostname={{ ansible_hostname }}'
     - name: enable and start zabbix_agent2 service
       systemd:
         name: zabbix-agent2
         state: started
         enabled: yes

